version: '3.4'

services:
  digitalbank.api.adm.transaction:
    image: ${DOCKER_REGISTRY-}digitalbankapiadmtransaction
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    secrets:
     - MYSQL_CONNECTIONSTRING
     - RABBITMQ_HOST
     - RABBITMQ_PASSWORD
     - RABBITMQ_TRANSACTION_COUNT
     - RABBITMQ_TRANSACTION_EXCHANGE
     - RABBITMQ_TRANSACTION_QUEUE
     - RABBITMQ_TRANSACTION_RETRY
     - RABBITMQ_USER_NAME
     - RETRY_ATTEMPT_TRANSACTION
     - INTERVAL_ATTEMPT_TRANSACTION
    ports:
     - '7003:80'
    networks:
     - digital-bank

networks:
  digital-bank:
    external: true 
  
secrets:
  MYSQL_CONNECTIONSTRING:
    file: secrets/MYSQL_CONNECTIONSTRING
  RABBITMQ_HOST:
    file: ./secrets/RABBITMQ_HOST
  RABBITMQ_PASSWORD:
    file: ./secrets/RABBITMQ_PASSWORD
  RABBITMQ_TRANSACTION_COUNT:
    file: ./secrets/RABBITMQ_TRANSACTION_COUNT
  RABBITMQ_TRANSACTION_EXCHANGE:
    file: ./secrets/RABBITMQ_TRANSACTION_EXCHANGE   
  RABBITMQ_TRANSACTION_QUEUE:
    file: ./secrets/RABBITMQ_TRANSACTION_QUEUE
  RABBITMQ_TRANSACTION_RETRY:
    file: ./secrets/RABBITMQ_TRANSACTION_RETRY
  RABBITMQ_USER_NAME:
    file: ./secrets/RABBITMQ_USER_NAME
  RETRY_ATTEMPT_TRANSACTION:
    file: ./secrets/RETRY_ATTEMPT_TRANSACTION
  INTERVAL_ATTEMPT_TRANSACTION:
    file: ./secrets/INTERVAL_ATTEMPT_TRANSACTION