version: '3.4'

services:
      
  mysql:
    extends:
         file: DigitalBank.MySQL/docker-compose.yml
         service: mysqldb 
    networks:
      - digital-bank
 
  rabbit:
    extends:
         file: DigitalBank.RabbitMQ/docker-compose.yml
         service: rabbitmq
    networks:
      - digital-bank

networks:
  digital-bank:
    driver: bridge 