version: '3.4'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    secrets:
     - MYSQL_ROOT_PASSWORD
     - MYSQL_DATABASE
     - MYSQL_USER
     - MYSQL_PASSWORD
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - '3307:3307'
    network_mode: "bridge"
      
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
     - $PWD/storage/rabbitmq:/var/lib/rabbitmq
    secrets:
     - RABBITMQ_ERLANG_COOKIE
     - RABBITMQ_DEFAULT_USER
     - RABBITMQ_DEFAULT_PASS
    environment:
      RABBITMQ_ERLANG_COOKIE: RABBITMQ_ERLANG_COOKIE
      RABBITMQ_DEFAULT_USER: RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: RABBITMQ_DEFAULT_PASS
    ports:
      - '15672:15672'
    network_mode: "bridge"

secrets:
  MYSQL_ROOT_PASSWORD:
    file: ./secrets/MYSQL_ROOT_PASSWORD
  MYSQL_DATABASE:
    file: ./secrets/MYSQL_DATABASE
  MYSQL_USER:
    file: ./secrets/MYSQL_USER
  MYSQL_PASSWORD:
    file: ./secrets/MYSQL_PASSWORD
  MYSQL_HOST:
    file: ./secrets/MYSQL_HOST
  MYSQL_PORT:
    file: ./secrets/MYSQL_PORT
  RABBITMQ_ERLANG_COOKIE:
    file: ./secrets/RABBITMQ_ERLANG_COOKIE
  RABBITMQ_DEFAULT_USER:
    file: ./secrets/RABBITMQ_DEFAULT_USER
  RABBITMQ_DEFAULT_PASS:
    file: ./secrets/RABBITMQ_DEFAULT_PASS
  JWT_SECRET:
    file: ./secrets/JWT_SECRET
  JWT_EXPIREHOURS:
    file: ./secrets/JWT_EXPIREHOURS
  ENCRYPTOR_SECRET:
    file: ./secrets/ENCRYPTOR_SECRET