version: '3.4'

services:
  digitalbank.api.pub.authenticate:
    image: digitalbank.api.pub.authenticate
    build:
      context: ./
      dockerfile: DigitalBank.Api.Pub.Authenticate/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    secrets:
     - MYSQL_CONNECTIONSTRING
     - JWT_SECRET
     - JWT_EXPIREHOURS
     - ENCRYPTOR_SECRET
    ports:
     - '5001:80'

secrets:
  MYSQL_CONNECTIONSTRING:
    file: ./secrets/MYSQL_CONNECTIONSTRING
  JWT_SECRET:
    file: ./secrets/JWT_SECRET
  JWT_EXPIREHOURS:
    file: ./secrets/JWT_EXPIREHOURS
  ENCRYPTOR_SECRET:
    file: ./secrets/ENCRYPTOR_SECRET
