version: '3.4'

services: 
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: digitalbank
      MYSQL_DATABASE: digitalbank
      MYSQL_USER: digitalbank
      MYSQL_PASSWORD: '!@12QWqw'
    ports:
      - '3306:3306'     
 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - '15672:15672'
    volumes:
     - $PWD/storage/rabbitmq:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=digitalbank
     - RABBITMQ_DEFAULT_USER=digitalbank
     - RABBITMQ_DEFAULT_PASS='!@12QWqw'
