version: '3.4'

services:

  digitalbank.worker.transaction:
    image: digitalbank.worker.transaction
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-Worker-Transaction
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    secrets:
     - MYSQL_CONNECTIONSTRING
     - RABBITMQ_HOST
     - RABBITMQ_PASSWORD
     - RABBITMQ_TRANSACTION_COUNT
     - RABBITMQ_TRANSACTION_EXCHANGE
     - RABBITMQ_TRANSACTION_QUEUE
     - RABBITMQ_TRANSACTION_RETRY
     - RABBITMQ_USER_NAME
     - RETRY_ATTEMPT_TRANSACTION
     - INTERVAL_ATTEMPT_TRANSACTION
    ports:
     - '9001:80'
      
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    hostname: mysqldb
    environment:
     - MYSQL_ROOT_PASSWORD=digitalbank
     - MYSQL_DATABASE=digitalbank
     - MYSQL_USER=digitalbank
     - MYSQL_PASSWORD=!@12QWqw
     - TZ=America/Sao_Paulo
    ports:
      - '3306:3306'  
    volumes:
      - /data:/var/lib/mysql 
    networks:
      - digital-bank
 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
     - /storage/rabbitmq:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=digitalbank
     - RABBITMQ_DEFAULT_USER=digitalbank
     - RABBITMQ_DEFAULT_PASS=!@12QWqw
    networks:
      - digital-bank

secrets:
  MYSQL_CONNECTIONSTRING:
    file: secrets/MYSQL_CONNECTIONSTRING
  RABBITMQ_HOST:
    file: ./secrets/RABBITMQ_HOST
  RABBITMQ_PASSWORD:
    file: ./secrets/RABBITMQ_PASSWORD
  RABBITMQ_TRANSACTION_COUNT:
    file: ./secrets/RABBITMQ_TRANSACTION_COUNT
  RABBITMQ_TRANSACTION_EXCHANGE:
    file: ./secrets/RABBITMQ_TRANSACTION_EXCHANGE   
  RABBITMQ_TRANSACTION_QUEUE:
    file: ./secrets/RABBITMQ_TRANSACTION_QUEUE
  RABBITMQ_TRANSACTION_RETRY:
    file: ./secrets/RABBITMQ_TRANSACTION_RETRY
  RABBITMQ_USER_NAME:
    file: ./secrets/RABBITMQ_USER_NAME
  RETRY_ATTEMPT_TRANSACTION:
    file: ./secrets/RETRY_ATTEMPT_TRANSACTION
  INTERVAL_ATTEMPT_TRANSACTION:
    file: ./secrets/INTERVAL_ATTEMPT_TRANSACTION

networks:
  digital-bank:
    driver: bridge 