version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: digitalbank
      MYSQL_DATABASE: digitalbank
      MYSQL_USER: digitalbank
      MYSQL_PASSWORD: '!@12QWqw'
    ports:
      - "3306:3306"
    network_mode: "bridge"
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
     - $PWD/storage/rabbitmq:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
     - RABBITMQ_DEFAULT_USER=mqadmin
     - RABBITMQ_DEFAULT_PASS=Admin123XX_
    ports:
      - "15672:15672"
    network_mode: "bridge"
