version: '3.4'

services:

  digitalbank.worker.transaction:
    build:
      context: ./DigitalBank.Worker.Transaction/
    command: docker-compose up -d
    networks:
      - digital-bank
    depends_on:
     - mysqldb
     - rabbitmq 

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    hostname: mysqldb
    environment:
     - MYSQL_ROOT_PASSWORD=digitalbank
     - MYSQL_DATABASE=digitalbank
     - MYSQL_USER=digitalbank
     - MYSQL_PASSWORD=!@12QWqw
     - TZ=America/Sao_Paulo
    ports:
      - '3306:3306'  
    volumes:
      - /data:/var/lib/mysql      
 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - digital-bank
    volumes:
     - /storage/rabbitmq:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=digitalbank
     - RABBITMQ_DEFAULT_USER=digitalbank
     - RABBITMQ_DEFAULT_PASS=!@12QWqw    
   
networks:
  digital-bank:
    driver: bridge 