version: '3.4'

services:
  mysqldb:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=digitalbank
     - MYSQL_DATABASE=digitalbank
     - MYSQL_USER=digitalbank
     - MYSQL_PASSWORD=!@12QWqw
    ports:
      - '3306:3306'  
    volumes:
      - 'docker_data:/data/var/lib/mysql'

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '15672:15672'
    volumes:
     - 'docker_data:/data/var/lib/rabbitmq'
    environment:
     - RABBITMQ_ERLANG_COOKIE=digitalbank
     - RABBITMQ_DEFAULT_USER=digitalbank
     - RABBITMQ_DEFAULT_PASS=!@12QWqw

  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
        - '9000:9000'
    volumes:
        - 'docker_data:/data/var/lib/portainer'
        - /var/run/docker.sock:/var/run/docker.sock
   
  digitalbank.migrations:
    build:
      context: DigitalBank.Migrations
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    secrets:
     - MYSQL_CONNECTIONSTRING
    ports:
     - '9002:80'
    depends_on:
     - rabbitmq
     - mysqldb
     - portainer
     
  digitalbank.worker.transaction:
    build:
      context: DigitalBank.Worker.Transaction
      dockerfile: Dockerfile
    deploy:
      replicas: 3
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    secrets:
     - MYSQL_CONNECTIONSTRING
     - RABBITMQ_HOST
     - RABBITMQ_PASSWORD
     - RABBITMQ_TRANSACTION_COUNT
     - RABBITMQ_TRANSACTION_EXCHANGE
     - RABBITMQ_TRANSACTION_QUEUE
     - RABBITMQ_TRANSACTION_RETRY
     - RABBITMQ_USER_NAME
     - RETRY_ATTEMPT_TRANSACTION
     - INTERVAL_ATTEMPT_TRANSACTION
    ports:
     - '9001:80'
    depends_on:
     - rabbitmq
     - mysqldb
     - portainer

  digitalbank.api.pub.transaction:
    build:
      context: DigitalBank.Api.Pub.Transaction
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    secrets:
     - MYSQL_CONNECTIONSTRING
     - RABBITMQ_HOST
     - RABBITMQ_PASSWORD
     - JWT_SECRET
     - ENCRYPTOR_SECRET
     - JWT_EXPIREHOURS
     - RABBITMQ_USER_NAME
    ports:
     - '5003:80'
    depends_on:
     - rabbitmq
     - mysqldb
     - portainer
     
  digitalbank.api.pub.digitalaccount:
    build:
      context: DigitalBank.Api.Pub.DigitalAccount
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    secrets:
     - MYSQL_CONNECTIONSTRING
     - ENCRYPTOR_SECRET
     - JWT_EXPIREHOURS
     - JWT_SECRET
    ports:
     - '5002:80'
    depends_on:
     - rabbitmq
     - mysqldb
     - portainer
     
  digitalbank.api.pub.authenticate:
    build:
      context: DigitalBank.Api.Pub.Authenticate
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    secrets:
     - MYSQL_CONNECTIONSTRING
     - ENCRYPTOR_SECRET
     - JWT_EXPIREHOURS
     - JWT_SECRET
    ports:
     - '5001:80'
    depends_on:
     - rabbitmq
     - mysqldb
     - portainer

  digitalbank.api.adm.transaction:
    build:
      context: DigitalBank.Api.Adm.Transaction
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    secrets:
     - MYSQL_CONNECTIONSTRING
     - ENCRYPTOR_SECRET
     - JWT_EXPIREHOURS
     - JWT_SECRET
    ports:
     - '7003:80'
    depends_on:
     - rabbitmq
     - mysqldb
     - portainer
     
  digitalbank.api.adm.digitalaccount:
    build:
      context: DigitalBank.Api.Adm.DigitalAccount
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    secrets:
     - MYSQL_CONNECTIONSTRING
     - ENCRYPTOR_SECRET
     - JWT_EXPIREHOURS
     - JWT_SECRET
    ports:
     - '7002:80'
    depends_on:
     - rabbitmq
     - mysqldb
     - portainer
     
  digitalbank.api.adm.authenticate:
    build:
      context: DigitalBank.Api.Adm.Authenticate
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    secrets:
     - MYSQL_CONNECTIONSTRING
     - ENCRYPTOR_SECRET
     - JWT_EXPIREHOURS
     - JWT_SECRET
    ports:
     - '7001:80'   
    depends_on:
     - rabbitmq
     - mysqldb
     - portainer

volumes:
    docker_data:
    
secrets:
  MYSQL_CONNECTIONSTRING:
    file: secrets/MYSQL_CONNECTIONSTRING
  RABBITMQ_HOST:
    file: ./secrets/RABBITMQ_HOST
  RABBITMQ_PASSWORD:
    file: ./secrets/RABBITMQ_PASSWORD
  RABBITMQ_TRANSACTION_COUNT:
    file: ./secrets/RABBITMQ_TRANSACTION_COUNT
  RABBITMQ_TRANSACTION_EXCHANGE:
    file: ./secrets/RABBITMQ_TRANSACTION_EXCHANGE   
  RABBITMQ_TRANSACTION_QUEUE:
    file: ./secrets/RABBITMQ_TRANSACTION_QUEUE
  RABBITMQ_TRANSACTION_RETRY:
    file: ./secrets/RABBITMQ_TRANSACTION_RETRY
  RABBITMQ_USER_NAME:
    file: ./secrets/RABBITMQ_USER_NAME
  RETRY_ATTEMPT_TRANSACTION:
    file: ./secrets/RETRY_ATTEMPT_TRANSACTION
  INTERVAL_ATTEMPT_TRANSACTION:
    file: ./secrets/INTERVAL_ATTEMPT_TRANSACTION
  ENCRYPTOR_SECRET:
    file: secrets/ENCRYPTOR_SECRET
  JWT_EXPIREHOURS:
    file: secrets/JWT_EXPIREHOURS
  JWT_SECRET:
    file: secrets/JWT_SECRET