FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS build

WORKDIR /src

COPY DigitalBank.Workers/DigitalBank.Worker.Transaction/DigitalBank.Worker.Transaction/DigitalBank.Worker.Transaction.csproj DigitalBank.Worker.Transaction/
COPY DigitalBank.Workers/DigitalBank.Worker.Transaction/DigitalBank.Worker.Transaction.Business/DigitalBank.Worker.Transaction.Business.csproj DigitalBank.Worker.Transaction.Business/
COPY DigitalBank.Workers/DigitalBank.Worker.Transaction/DigitalBank.Worker.Transaction.Repository/DigitalBank.Worker.Transaction.Repository.csproj DigitalBank.Worker.Transaction.Repository/

RUN dotnet restore DigitalBank.Worker.Transaction/DigitalBank.Worker.Transaction.csproj

COPY . .

WORKDIR /src/DigitalBank.Worker.Transaction
RUN dotnet build DigitalBank.Worker.Transaction.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish DigitalBank.Worker.Transaction.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "DigitalBank.Worker.Transaction.dll"]