version: '3.4'

services:
  digitalbank.api.adm.digitalaccount:
    image: ${DOCKER_REGISTRY-}digitalbankapiadmdigitalaccount
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    secrets:
     - MYSQL_CONNECTIONSTRING
     - ENCRYPTOR_SECRET
     - JWT_EXPIREHOURS
     - JWT_SECRET
    ports:
     - '7002:80'
    networks:
     - digital-bank

networks:
  digital-bank:
    external: true 
      
secrets:
  ENCRYPTOR_SECRET:
    file: secrets/ENCRYPTOR_SECRET
  JWT_EXPIREHOURS:
    file: secrets/JWT_EXPIREHOURS
  JWT_SECRET:
    file: secrets/JWT_SECRET
  MYSQL_CONNECTIONSTRING:
    file: secrets/MYSQL_CONNECTIONSTRING