version: '3.4'

services:
  digitalbank.migrations:
    image: ${DOCKER_REGISTRY-}digitalbankmigrations
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    secrets:
     - MYSQL_CONNECTIONSTRING
    ports:
     - '9002:80'

secrets:
  MYSQL_CONNECTIONSTRING:
    file: ./secrets/MYSQL_CONNECTIONSTRING