version: '3.4'

services:

  digitalbank.migration:
    image: digitalbank.migration
    container_name: digitalbank.migration
    build:
      context: ./
      dockerfile: DigitalBank.Migration/DockerFile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    secrets:
     - MYSQL_CONNECTIONSTRING
    ports:
     - '9002:80'
     
secrets:
  MYSQL_CONNECTIONSTRING:
    file: ./secrets/MYSQL_CONNECTIONSTRING