version: '3.4'

services:
  digitalbank.api.pub.transaction:
    image: ${DOCKER_REGISTRY-}digitalbankapipubtransaction
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    secrets:
     - MYSQL_CONNECTIONSTRING
     - RABBITMQ_HOST
     - RABBITMQ_PASSWORD
     - JWT_SECRET
     - ENCRYPTOR_SECRET
     - JWT_EXPIREHOURS
     - RABBITMQ_USER_NAME

    ports:
     - '5003:80'
    networks:
     - digital-bank

networks:
  digital-bank:
    external: true 
  
secrets:
  ENCRYPTOR_SECRET:
    file: secrets/ENCRYPTOR_SECRET
  JWT_EXPIREHOURS:
    file: secrets/JWT_EXPIREHOURS
  JWT_SECRET:
    file: secrets/JWT_SECRET
  MYSQL_CONNECTIONSTRING:
    file: secrets/MYSQL_CONNECTIONSTRING
  RABBITMQ_HOST:
    file: ./secrets/RABBITMQ_HOST
  RABBITMQ_PASSWORD:
    file: ./secrets/RABBITMQ_PASSWORD
  RABBITMQ_USER_NAME:
    file: ./secrets/RABBITMQ_USER_NAME
