FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.2-sdk AS build

WORKDIR /src

COPY DigitalBank.Migrations/DigitalBank.Migration/DigitalBank.Migration.csproj DigitalBank.Migration/

RUN dotnet restore DigitalBank.Migration/DigitalBank.Migration.csproj

COPY . .

WORKDIR /src/DigitalBank.Migration
RUN dotnet build DigitalBank.Migration.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish DigitalBank.Migration.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "DigitalBank.Migration.dll"]