version: '3.4'

services:
  digitalbank.api.adm.authenticate:
    image: ${DOCKER_REGISTRY-}digitalbankapiadmauthenticate
    build:
      context: .
      dockerfile: DigitalBank.Api.Adm.Authenticate/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    secrets:
     - MYSQL_CONNECTIONSTRING
     - ENCRYPTOR_SECRET
     - JWT_EXPIREHOURS
     - JWT_SECRET
    ports:
     - '7001:80'
    networks:
     - digital-bank

networks:
  digital-bank:
    external: true 
 
secrets:
  ENCRYPTOR_SECRET:
    file: secrets/ENCRYPTOR_SECRET
  JWT_EXPIREHOURS:
    file: secrets/JWT_EXPIREHOURS
  JWT_SECRET:
    file: secrets/JWT_SECRET
  MYSQL_CONNECTIONSTRING:
    file: secrets/MYSQL_CONNECTIONSTRING